server.port=8081

# 1. Database Connection (옵션 두 개를 &로 연결했습니다)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/ess?createDatabaseIfNotExist=true&disableSspi=true
spring.datasource.username=root
spring.datasource.password=1234

# 2. JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# 3. MyBatis
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.ess.erp.domain

# 4. JSP View
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp